<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3kxxnbx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3kxxnbx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3kxxnbx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3kxxnbx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3kxxnbx\appDevDebugProjectContainer(array(
    'container.build_hash' => '3kxxnbx',
    'container.build_id' => '2db4a163',
    'container.build_time' => 1534055989,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3kxxnbx');
